#!/usr/bin/env python
#-*- coding = utf-8 -*-
import os
from ClassPrint import *


class ClassConfig:
    config_content_old = ""
    def __init__(self, build_path, config_filename, toolchain, toolchain_prefix):
        self.config_path = build_path + os.path.split() + "config"
        self.config_filename = self.config_path + os.path.split() + config_filename
        if os.path.exists(self.config_filename):
            with open(self.config_filename) as f:
                self.config_content_old = f.read()
        self.header = "# This file is automatically generated by the script, please do not modify the content!\n\n"
        self.config_content = header
        self.update_config = False
        self.toolchain = toolchain
        self.toolchain_prefix = toolchain_prefix

    def add_toolchain(self):
        if self.toolchain.strip() != "":
            if not os.path.exists(self.toolchain):
                PRT.error("invalid toolchain path:", self.toolchain)
                exit(1)
            self.update_config = True
            self.config_content += 'CONFIG_TOOLCHAIN_PATH="'+ self.toolchain.strip().replace("\\","/") +'"\n'
        if self.toolchain_prefix.strip() != "":
            self.update_config = True
            self.config_content += 'CONFIG_TOOLCHAIN_PREFIX="' + self.toolchain_prefix.strip().replace("\\","/") + '"\n'
        self.config_content += '\n'

    def update_config(self):
        self.add_toolchain()
        if self.update_config and self.config_content != self.config_content_old:
            with open(self.config_filename, "w") as f:
                f.write(self.config_content)
            if os.path.exists(self.config_path + os.path.split() + "global_config.mk"):
                os.remove(self.config_path + os.path.split() + "global_config.mk")
            PRT.Complete("generate config file at {}".format(self.config_filename))
